### ISSUE TITLE
Unable to run Windows dockerd container as HostProcess

### ISSUE THREAD

**Issue by jrbe228** [lippertmarkus/lippertmarkus#1]
When attempting to use the YAML in this [article](https://lippertmarkus.com/2022/04/22/win-img-docker-hostprocess-k8s/), I get the following error on an AKS cluster - 

> 'dockerd.exe' is not recognized as an internal or external command

![Image](https://github.com/user-attachments/assets/1887148e-9732-41de-a0e1-0d4c951dbd9f)

As a debugging step, I tried the HostProcess container from a preceding [blog post](https://lippertmarkus.com/2021/11/05/k8s-win22-hostprocess/). Running this pod gave the expected logs - 

![Image](https://github.com/user-attachments/assets/e905d4c9-919e-464f-89f7-8ad3b2b6861b)

**Comment by jrbe228** [comment]
Some progress here. After inspecting the folder structure, it seems adjusting `workingDir` avoids the error with dockerd.exe: 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dockerd
spec:
  selector:
    matchLabels:
      app: dockerd
  template:
    metadata:
      labels:
        app: dockerd
    spec:
      containers:
      - name: dockerd
        image: lippertmarkus/dockerd:20.10.23
        workingDir: "C:\\hpc\\docker"
        #command:
        #- ping
        #args:
        #- -t
        #- localhost
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
```

**Comment by jrbe228** [comment]
Got it working :) 
Needed to use Win Server 2022 based images. 
```
 apiVersion: batch/v1
 kind: Job
 metadata:
   name: docker-build-example
 spec:
   template:
     spec:
       containers:
       - name: docker
         image: ghcr.io/kenmuse/arc-windows-runner:v2.321.0
         command: ["cmd", "/c"]
         args: ["(echo FROM mcr.microsoft.com/windows/nanoserver:ltsc2022 & echo RUN echo helloworld ) | docker build -t test -"]
         volumeMounts:
         - mountPath: \\.\pipe\docker_engine
           name: dockersock
       securityContext:
         windowsOptions:
           runAsUserName: "ContainerAdministrator"
       restartPolicy: Never
       volumes:
       - name: dockersock
         hostPath:
           path: \\.\pipe\docker_engine
           type: null
       nodeSelector:
         # needs to be identical to the DaemonSet
         kubernetes.io/os: windows
   backoffLimit: 2
```

Results in this pod log: 

![Image](https://github.com/user-attachments/assets/1a16ac3a-57f8-4c03-ad58-647f2848cf26)
